### PR TITLE
expose redigo dial opts

### PR DESCRIPTION
**Pull request by morus12**
Expose redigo dial options.

### CODE REVIEW

**Comment by filipecosta90** [comment]
Hi there @morus12 , thank you for the PR but I believe there are two reasons not to merge it:

- The changes to  `NewSingleHostPool()` and `NewMultiHostPool()` are breaking changes, meaning anyone upgrading their client would suddenly break their apps.

- The redisearch-go already contains `NewClientFromPool()` which creates a new Client with the given pool and index name. You can add any pool options/configs to a vanilla redigo pool and then create the search client on top of it. This is beneficial when working with multiple modules, or 1 module and vanilla, or with more advanced connection types like secure ones. 

Can you check the NewClientFromPool example and see if that function matches all you requirements?
 https://pkg.go.dev/github.com/RediSearch/redisearch-go@v1.1.1/redisearch#example-NewClientFromPool

**Comment by morus12** [comment]
Hi, I wanted to use NewMultiHostPool with TLS. As far as I know, it's not possible now.

**Comment by filipecosta90** [comment]
> Hi, I wanted to use `NewMultiHostPool` with TLS. As far as I know, it's not possible now.

@morus12 you're 100% right it's not possible now. If that is the requirement I would suggest changing this PR to add:
- NewClientFromMultiHostPool(pools *MultiHostPool, name string) 
- NewMultiHostPoolFromPoolsMap(hosts []string, pools map[string]*redis.Pool) - or a bettername. 

Still, I don't see an exact usage for the MultiHostPool given it randomizes the pool connection fetching (IMHO I would argue that we should even deprecate MultiHostPool). Do you have an use case for it?

**Comment by morus12** [comment]
@filipecosta90 TLS doesn't change the use case for MultiHostPool. Maybe this function should not exist in the first place.

I wanted to ask about the Redis cluster - are you going to support it?

**Pull request closed without merging**
